name: Qodo Mention Bot

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  respond:
    if: ${{ startsWith(github.event.comment.body, '@qodo ') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodo Mention Bot
        uses: qododavid/qodo-gen-cli@main
        with:
          prompt: "qodo-mention"
          agentfile: "${{ github.workspace }}/agent.toml"
          key-value-pairs: |
            event_path: ${{ github.event_path }}
        env:
          QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
